<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tokemak</name>
   <tag></tag>
   <elementGuidId>7f44c446-a8b1-4864-85fd-28fb7269fda2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div[4]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93e85111-d75f-466c-82ca-018d2308711a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tokemak</value>
      <webElementGuid>a928c598-0ab3-4947-b8a2-c2675683af87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_myBalanceContainer__yhuRK&quot;]/div[@class=&quot;styles_gridContainer__LiPOa&quot;]/div[@class=&quot;styles_cardContainer__jkBND styles_cardContent__vGB99&quot;]/div[@class=&quot;styles_coinCard__5Z-kA&quot;]/div[@class=&quot;styles_coinCardTitle__Fgz5K&quot;]/span[1]</value>
      <webElementGuid>d54d198b-4125-47a6-b9f6-fd6f84fe50c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[4]/div/div/span</value>
      <webElementGuid>0a14e5d0-9b89-4f8b-a529-1b07b406ec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrow'])[3]/following::span[2]</value>
      <webElementGuid>e15d70db-3e7e-453b-b426-b8283a93341a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[3]/following::span[4]</value>
      <webElementGuid>dd1ec7a8-ae9e-430e-adaf-84be3401a94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[4]/preceding::span[1]</value>
      <webElementGuid>b110b56d-ea32-4439-a4ad-5da68cd0b831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Balance'])[4]/preceding::span[3]</value>
      <webElementGuid>4c735e77-4cf2-4c9d-ab94-a6e6930ef8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tokemak']/parent::*</value>
      <webElementGuid>a98b48e8-0354-4487-944d-6ffae7a3cfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span</value>
      <webElementGuid>e60c2e15-354d-4cd3-bbf8-ba56d76bf971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Tokemak' or . = ' Tokemak')]</value>
      <webElementGuid>2e77d9d6-7812-4254-8c86-f29edb2a42cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
