<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_longterm</name>
   <tag></tag>
   <elementGuidId>017082d3-a7ce-4626-b91d-07f3e7daf605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.styles_radioLabel__Zi5PW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div/div/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b820fab-93aa-48dc-933d-3f34b00de884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>longTerm</value>
      <webElementGuid>06369315-57e6-47b5-a83d-032b42761747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_radioLabel__Zi5PW</value>
      <webElementGuid>910139dc-d9f8-413c-9808-1221696b390a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Long Term</value>
      <webElementGuid>d03a127f-9eb5-4f40-8caa-6f58b888b9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_loanType__EB8LB&quot;]/div[@class=&quot;styles_radiogroup__aEjKC&quot;]/span[@class=&quot;styles_radioElementGroup__4hvZf&quot;]/label[@class=&quot;styles_radioLabel__Zi5PW&quot;]</value>
      <webElementGuid>17b76aa6-8cbd-4878-bffa-b31bbad047c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div/div/span/label</value>
      <webElementGuid>b0b3f7bd-6452-487c-88b9-4894396881b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrow'])[1]/following::label[2]</value>
      <webElementGuid>dfac1826-9159-42d4-9f3e-f53b61be3677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lend'])[1]/following::label[2]</value>
      <webElementGuid>76790b40-3831-4247-955b-15010ddc8b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intraday'])[1]/preceding::label[1]</value>
      <webElementGuid>c0bce4c5-c3ed-416d-a528-aec04189d92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evergreen'])[1]/preceding::label[2]</value>
      <webElementGuid>35fe3b32-1626-4575-b1d3-583168181966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Long Term']/parent::*</value>
      <webElementGuid>af76c01c-34ac-4d34-bf04-fe67632de7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>eb90dfbb-3690-4b5d-aefe-94c52358b9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Long Term' or . = 'Long Term')]</value>
      <webElementGuid>887318a9-7c63-40e9-9705-267daf9db331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
