<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_snx</name>
   <tag></tag>
   <elementGuidId>0a0d21dd-d194-43f5-b677-49d1a71912ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[7]/div/div[2]/div[2]/div[2]/div[2]/ul/li[6]/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>7673e016-d2e8-4521-ab0b-bd477b844aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Synthetix Network Token</value>
      <webElementGuid>1718085f-26d4-496c-a573-19d6d93076dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_collateralAssetId__VljHv&quot;]/div[@class=&quot;styles_selectable__hOZhE&quot;]/div[@class=&quot;styles_modal__5D1PS styles_modal__Q+Jxv&quot;]/div[@class=&quot;styles_modalContainer__ognAv styles_modalContainer__KMm73&quot;]/div[@class=&quot;styles_dialogContainer__pC5sT&quot;]/div[@class=&quot;styles_assetsListContainer__t4tZV&quot;]/ul[@class=&quot;styles_assetsList__1LLmE&quot;]/li[6]/div[1]/h6[1]</value>
      <webElementGuid>758f4ebd-aac2-496b-880b-d32dfee3a4ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[7]/div/div[2]/div[2]/div[2]/div[2]/ul/li[6]/div/h6</value>
      <webElementGuid>9b831807-aa08-4816-94e3-840fdf49d94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SNX'])[1]/following::h6[1]</value>
      <webElementGuid>42b9c7bf-2718-443d-9fb6-ace242ee7a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bitcoin Cash'])[1]/following::h6[1]</value>
      <webElementGuid>a103ba56-ed77-4144-8504-e2b703c9ccc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USDC'])[1]/preceding::h6[1]</value>
      <webElementGuid>9645ba89-7fc5-47bb-a1fe-518ebf83f49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD Coin'])[1]/preceding::h6[1]</value>
      <webElementGuid>24ef92c0-19f9-4a75-b71b-b727c9a81851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Synthetix Network Token']/parent::*</value>
      <webElementGuid>3a80f4b0-73d5-4f5b-8342-31c613da7e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/h6</value>
      <webElementGuid>2e745b42-872c-4b58-9813-01f454c26bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Synthetix Network Token' or . = 'Synthetix Network Token')]</value>
      <webElementGuid>8fa761a6-89b6-443c-90e9-fe3ca4f9261b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
