<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_collateral_tokemak</name>
   <tag></tag>
   <elementGuidId>218ed708-105c-4456-aa07-fb2c27a62ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[6]/div/div[2]/div[2]/div[2]/div[2]/ul/li[8]/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>cc6a9261-a78e-464e-9456-b0ab933a583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tokemak</value>
      <webElementGuid>4a40774a-dade-4c87-a85a-31c5b897319f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_collateralAssetId__VljHv&quot;]/div[@class=&quot;styles_selectable__hOZhE&quot;]/div[@class=&quot;styles_modal__5D1PS styles_modal__Q+Jxv&quot;]/div[@class=&quot;styles_modalContainer__ognAv styles_modalContainer__KMm73&quot;]/div[@class=&quot;styles_dialogContainer__pC5sT&quot;]/div[@class=&quot;styles_assetsListContainer__t4tZV&quot;]/ul[@class=&quot;styles_assetsList__1LLmE&quot;]/li[8]/div[1]/h6[1]</value>
      <webElementGuid>8a000597-957e-4bc0-a145-8d3c65762d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[6]/div/div[2]/div[2]/div[2]/div[2]/ul/li[8]/div/h6</value>
      <webElementGuid>029cd61e-87d0-40fd-96bd-98c6ea120dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOKE'])[1]/following::h6[1]</value>
      <webElementGuid>8524324c-ad62-42c3-921f-2fa84fb9a5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD Coin'])[1]/following::h6[1]</value>
      <webElementGuid>c288c4ea-5526-4b4b-bed6-b52d850a8441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WBTC'])[1]/preceding::h6[1]</value>
      <webElementGuid>aebcc05d-ba9e-4f85-9a4e-8311139ab008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tokemak']/parent::*</value>
      <webElementGuid>785a00ec-8d49-44c3-8e33-daae3c772a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/h6</value>
      <webElementGuid>9664fec5-493c-4811-bf02-7b29fa54862b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Tokemak' or . = 'Tokemak')]</value>
      <webElementGuid>2de1a7dc-c954-420d-b815-07bd7d3ab7d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
