<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ETHEREUM</name>
   <tag></tag>
   <elementGuidId>bad18b10-c997-43b4-aae8-6a5e37b2ca28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.styles_tabs__i1BEH.styles_contained__YvtOM > button[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9468edbe-f16f-4fb8-a9ff-cc4c291a9db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d48e604f-ae60-4e2a-8a77-3a3f8673d9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be8da5c5-34c6-4d5b-b075-dfea65a219e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ETHEREUM</value>
      <webElementGuid>add4a20a-705e-47ff-8cd2-c4f134bc3495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[2]/nav[@class=&quot;styles_tabs__i1BEH styles_contained__YvtOM&quot;]/button[1]</value>
      <webElementGuid>739a3363-d036-4e03-891b-6637c45a7d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>2f634f90-529c-492a-a048-69b31a46f7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/nav/button</value>
      <webElementGuid>b6dcaff4-b4d8-492d-9ba7-7bebe1bcf097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add New Wallet'])[1]/following::button[1]</value>
      <webElementGuid>d4e6ccac-135a-4271-93c4-32f29b2b52ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Balances &amp; Credits'])[1]/following::button[2]</value>
      <webElementGuid>c0f52643-75fd-4e68-aebd-904a79c07b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BITCOIN'])[1]/preceding::button[1]</value>
      <webElementGuid>d8daa86d-ee7b-469a-ba81-c81e5bfa70fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BITCOIN CASH'])[1]/preceding::button[2]</value>
      <webElementGuid>0c4a578d-c531-4b30-8268-1356f208eef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ETHEREUM']/parent::*</value>
      <webElementGuid>f95a948c-1271-48f6-a47a-9eea585eef2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button</value>
      <webElementGuid>12186026-e738-4dac-a969-4b30adfc75bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ETHEREUM' or . = 'ETHEREUM')]</value>
      <webElementGuid>9d747531-efb2-40c9-95db-1c3e23b0ecd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
