<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ethereum</name>
   <tag></tag>
   <elementGuidId>386d3a87-cafe-41b8-97f0-23dac801478f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_coinCardTitle__Fgz5K > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50213c28-e586-435e-b640-52f121a1e181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ethereum</value>
      <webElementGuid>1138dbf4-5e7c-4ddc-bfd1-bf278bdaa399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_myBalanceContainer__yhuRK&quot;]/div[@class=&quot;styles_gridContainer__LiPOa&quot;]/div[@class=&quot;styles_cardContainer__jkBND styles_cardContent__vGB99&quot;]/div[@class=&quot;styles_coinCard__5Z-kA&quot;]/div[@class=&quot;styles_coinCardTitle__Fgz5K&quot;]/span[1]</value>
      <webElementGuid>c40da8aa-3530-4bb0-99e5-247952565eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div/div/div/span</value>
      <webElementGuid>48377727-5b21-4863-b3ad-051ca6ad8a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LITECOIN'])[1]/following::span[1]</value>
      <webElementGuid>adcfeef4-3c3d-4c43-ac8a-1298a64a4c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BITCOIN CASH'])[1]/following::span[1]</value>
      <webElementGuid>c3f46946-38ac-4da6-87ad-edd26f443011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::span[1]</value>
      <webElementGuid>e5068eec-f6e8-4f5f-bf92-d97e58916001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Balance'])[1]/preceding::span[3]</value>
      <webElementGuid>f6ee58da-fac6-4327-be7b-9e8fe914d0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ethereum']/parent::*</value>
      <webElementGuid>51e43ae2-9d91-4d4c-ac21-18849ce9f5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
      <webElementGuid>98a348eb-d9bb-4cf1-b383-eab7a4590ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Ethereum' or . = ' Ethereum')]</value>
      <webElementGuid>3c658c40-fc6e-4c98-83a3-5f2b526c233e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
