<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validate_pending_invite</name>
   <tag></tag>
   <elementGuidId>005c9133-b0c2-4795-bd51-027c5301c3ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_tableCell__4RsDS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb818405-d770-460b-b956-4376e16248a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_tableCell__4RsDS</value>
      <webElementGuid>b0e3050f-0d6d-4270-aa2b-298164e98b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ramoncito.lootgnitset@gmail.com</value>
      <webElementGuid>97910cfc-6242-4667-a198-1fedea00ed30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_usersContainer__jzXgW&quot;]/div[2]/div[1]/div[@class=&quot;styles_sentTable__tI2no&quot;]/div[@class=&quot;styles_tableWrapper__4+kih&quot;]/table[@class=&quot;styles_membraneTable__F4Lyo&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;styles_tableCell__4RsDS&quot;]</value>
      <webElementGuid>b754ae1a-1f79-4ef4-86ff-4da5982a3112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div</value>
      <webElementGuid>f19246d3-cefb-4373-84e3-4ceb17807f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-MAIL'])[1]/following::div[3]</value>
      <webElementGuid>b846b570-7814-4353-b6b5-5183c7d90c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sent'])[1]/following::div[6]</value>
      <webElementGuid>61f4d07b-6a18-4da1-88db-740338ef6fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Invite'])[1]/preceding::div[1]</value>
      <webElementGuid>b564602d-1ccb-45bb-89fb-cccdda3f8376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Reminder'])[1]/preceding::div[4]</value>
      <webElementGuid>08936cd6-2f73-43f1-9114-909436728858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ramoncito.lootgnitset@gmail.com']/parent::*</value>
      <webElementGuid>b0800885-5542-4d72-86f2-e0bd1d314fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>e98ac7da-0ca3-4fc2-8de8-6814d748aa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ramoncito.lootgnitset@gmail.com' or . = 'ramoncito.lootgnitset@gmail.com')]</value>
      <webElementGuid>0a7b252c-f04a-4cc2-82c1-91730e9becc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
