<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blockchain_eth</name>
   <tag></tag>
   <elementGuidId>7d750cdc-7f21-4c08-9760-693234c2bfd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/label/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_fieldInput__IDY-B</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc07f4e2-e2d8-4416-8565-efc1c0d3c861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_fieldInput__IDY-B</value>
      <webElementGuid>6f8bd829-c2ea-45cf-8aae-2b5ac64c48f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2caf430-385d-4de8-839c-c5cad0a0827f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_myBalanceHeader__8eqxI&quot;]/div[@class=&quot;styles_selectable__ja4NI&quot;]/div[@class=&quot;styles_modal__5D1PS styles_modal__dX4LE&quot;]/div[@class=&quot;styles_modalContainer__ognAv&quot;]/div[@class=&quot;styles_dialogContainer__ICG6E&quot;]/div[@class=&quot;styles_tokenAddressContainer__xR7hS&quot;]/label[1]/div[@class=&quot;styles_selectable__gksaM styles_customDisabled__d8wqy&quot;]/div[@class=&quot;styles_fieldInput__IDY-B&quot;]</value>
      <webElementGuid>e0589334-c9fe-4bad-85a1-95266c2cdea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/label/div/div</value>
      <webElementGuid>24010313-d360-49a3-a5ad-49576e0de72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please, enter the contract address'])[1]/following::div[3]</value>
      <webElementGuid>1933113b-2a7b-48b3-aaa8-daeae7141fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethereum'])[1]/preceding::div[1]</value>
      <webElementGuid>66a1abaa-13e6-444b-a16e-1860625fb947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WBTC'])[1]/preceding::div[3]</value>
      <webElementGuid>07b66ece-6dcb-4e41-a58a-f38891ee4b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div</value>
      <webElementGuid>83b4381c-8167-4d3b-84e9-2fbdea0f6305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
