<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_collateral_limit</name>
   <tag></tag>
   <elementGuidId>2ca65b07-644b-4aa7-9e14-980bb45a9e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='collateral_bands']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;collateral_bands&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>874504c1-b631-4f98-852e-a8ed088701d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>24c4dffe-24f9-4277-90b6-0d4bb0da7174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collateral_bands</value>
      <webElementGuid>10a4ba80-3fa2-4061-bd41-fe027d7b2e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>field_collateral_bands</value>
      <webElementGuid>3c118b8c-ac24-4989-8441-66b1c4adb8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>d0f7f212-b4c9-4f99-8672-0d8edea80e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__sEMsJ</value>
      <webElementGuid>4b43c67c-0ddc-45df-827f-36d9c4203ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>4abad5c4-757a-4230-86da-ff02bad5c65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_collateralBands__cLJ6m&quot;]/div[@class=&quot;styles_sufixWrapper__qozVh&quot;]/input[@class=&quot;styles_input__sEMsJ&quot;]</value>
      <webElementGuid>e2e32efd-206a-4b39-aabb-8acaf1261b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='collateral_bands']</value>
      <webElementGuid>78dfc6e8-bdec-41a6-8a65-283ba19c0bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[9]/div/input</value>
      <webElementGuid>0702c0ef-00cd-4a44-8fc6-f5b51445ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>948938d7-bb17-4fe7-b94e-c2056583ee39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'collateral_bands']</value>
      <webElementGuid>bee45aac-9181-45a9-8955-c968dc0cd728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
