<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_longterm</name>
   <tag></tag>
   <elementGuidId>5e322a08-c2f1-454b-86c9-5f02beff871c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div/div/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.styles_radioLabel__Zi5PW</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>14f1a9fc-757d-4f71-87e3-cff2b5840ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>longTerm</value>
      <webElementGuid>bc189f52-97b6-48ab-9ed1-69dc1743b380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_radioLabel__Zi5PW</value>
      <webElementGuid>6cca31ef-3fd3-45d0-baf9-236c0e13da08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Long Term</value>
      <webElementGuid>e8172587-c8e6-4920-bd9d-aade549e8dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_loanType__EB8LB&quot;]/div[@class=&quot;styles_radiogroup__aEjKC&quot;]/span[@class=&quot;styles_radioElementGroup__4hvZf&quot;]/label[@class=&quot;styles_radioLabel__Zi5PW&quot;]</value>
      <webElementGuid>4f67f577-1ec1-43c7-a0b3-afd3dc30bc4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div/div/span/label</value>
      <webElementGuid>b6bffa0b-c5ce-43e3-ace5-d006ae780716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrow'])[1]/following::label[2]</value>
      <webElementGuid>a328b6c7-dd1a-4af2-8820-98474231e13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lend'])[1]/following::label[2]</value>
      <webElementGuid>55873bd3-d26e-4c1f-a1b8-35f1206f4352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intraday'])[1]/preceding::label[1]</value>
      <webElementGuid>fbd024e4-d652-487e-8af0-b4279d0048f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evergreen'])[1]/preceding::label[2]</value>
      <webElementGuid>5e4ce9d3-9061-4ce6-997f-e4f283cf543e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Long Term']/parent::*</value>
      <webElementGuid>fb275279-2f9c-402c-959b-1811f62d067d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>8fb89a1e-2910-4f3f-b22b-651e1f53c376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Long Term' or . = 'Long Term')]</value>
      <webElementGuid>ed684bde-1bf2-4917-b3f2-9dc9d3d0fa48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
