<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_collateral_tokemak</name>
   <tag></tag>
   <elementGuidId>5a908821-2a10-4c6d-a4c2-d71732030483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[6]/div/div[2]/div[2]/div[2]/div[2]/ul/li[8]/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>b5b2118c-1981-457b-b8f4-674681edf249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tokemak</value>
      <webElementGuid>f39db231-c316-4359-8661-ddf74bcc10ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_collateralAssetId__VljHv&quot;]/div[@class=&quot;styles_selectable__hOZhE&quot;]/div[@class=&quot;styles_modal__5D1PS styles_modal__Q+Jxv&quot;]/div[@class=&quot;styles_modalContainer__ognAv styles_modalContainer__KMm73&quot;]/div[@class=&quot;styles_dialogContainer__pC5sT&quot;]/div[@class=&quot;styles_assetsListContainer__t4tZV&quot;]/ul[@class=&quot;styles_assetsList__1LLmE&quot;]/li[8]/div[1]/h6[1]</value>
      <webElementGuid>2ba78dbf-1a6d-4236-b304-2ba3cb946f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[6]/div/div[2]/div[2]/div[2]/div[2]/ul/li[8]/div/h6</value>
      <webElementGuid>4a51b8cd-08e5-4d42-a3a0-b54e15769513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOKE'])[1]/following::h6[1]</value>
      <webElementGuid>7fd92d57-18a8-46cf-a5bb-a77b91bc7c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD Coin'])[1]/following::h6[1]</value>
      <webElementGuid>bd79cf6f-643a-4464-95cd-5cf409123286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WBTC'])[1]/preceding::h6[1]</value>
      <webElementGuid>1885e05b-8512-4d10-8116-84da66ea03d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tokemak']/parent::*</value>
      <webElementGuid>78fa9221-78fe-4d3a-aea8-7a3958de676f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/h6</value>
      <webElementGuid>6a79cf7d-1377-4dc4-bf01-d42da5bf94a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Tokemak' or . = 'Tokemak')]</value>
      <webElementGuid>ee8cfb15-342a-44a4-9f2b-e3c87a396812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
