<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fuera_modal</name>
   <tag></tag>
   <elementGuidId>7e86c5fb-a305-417e-81e8-5f6767821de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/form/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_signInForm__i2b4C</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd5a6d24-e67c-4aa3-a69f-c888c04d2702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_signInForm__i2b4C</value>
      <webElementGuid>ee32db70-aee4-4129-baa3-ed8732d12bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EmailPasswordNext Sign Up Forgot Password </value>
      <webElementGuid>243f0d20-edc7-4d45-98ab-2d4d2562732b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_splash__GTouU&quot;]/form[1]/div[1]/div[@class=&quot;styles_responsiveAbsolutFix__bCkQO&quot;]/div[@class=&quot;styles_container__0Fbqk&quot;]/div[@class=&quot;styles_signInForm__i2b4C&quot;]</value>
      <webElementGuid>aa8ad18d-dc54-4ecb-8b4a-33cd94d5abe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div</value>
      <webElementGuid>326d0edf-98f5-495e-8064-42cb14e3d43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membrane'])[2]/following::div[4]</value>
      <webElementGuid>be11d32e-e9d8-456f-b181-d52f8cd6eb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>5644a709-eec4-4632-94f1-2ab60e624c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EmailPasswordNext Sign Up Forgot Password ' or . = 'EmailPasswordNext Sign Up Forgot Password ')]</value>
      <webElementGuid>dc657621-f4d9-4e4f-a89a-8a6ff689e9bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
