<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_token</name>
   <tag></tag>
   <elementGuidId>31714283-0e3e-49a5-bdd6-8fdbaa796072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.styles_backgroundFocus__6BGT1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36a99e6c-f545-4143-9bb5-7ca9e7243854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_backgroundFocus__6BGT1</value>
      <webElementGuid>cdf3b33f-a5d8-4714-895c-d00ae5f02d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>a2497d54-491e-475b-ae65-b372494593f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>2483a9b9-d588-450a-a4fd-2e5e32e58f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_splash__GTouU&quot;]/form[1]/div[@class=&quot;styles_twoFactorContainer__IMV+w&quot;]/div[@class=&quot;styles_twoFactorForm__BqmYE&quot;]/div[1]/div[@class=&quot;styles_digitCode__8BMyw&quot;]/div[@class=&quot;styles_inputGroup__hUuTN&quot;]/input[@class=&quot;styles_backgroundFocus__6BGT1&quot;]</value>
      <webElementGuid>363ab521-ee3b-4948-ba4e-ecc438777be0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>009d7b7a-29e6-4930-9282-2f590baacf36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div/div/input</value>
      <webElementGuid>e1025392-fe9b-4dac-a790-85ea29ff2e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3091c4ce-32da-4578-835f-982e9bd92981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
