<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>1c04c536-60e9-4a6d-b9dc-3110c5ed3a1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a4b2d5e-a67e-4ec2-9a8f-cb4cd45b2b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1eac7d8b-10d1-4ea7-96ff-a9dc8139740d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>12db5c73-6aa5-40cc-b4c3-87c3ce39ba09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>field_password</value>
      <webElementGuid>f8d26ee8-8e54-45b6-84d5-270f0514343d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>71224451-bcaf-4507-a05d-4a584fb60c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__sEMsJ</value>
      <webElementGuid>45d6ed84-3fa0-4e1c-af79-498acf28a833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert your password</value>
      <webElementGuid>5446f4a5-61c1-4a9b-87ab-7c105526f9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>qc@##Pw5%xyYy$sD^6GPQZx8Co5uYpwk!ncBHf</value>
      <webElementGuid>2a5f9912-37ae-4d04-a468-39f32369e4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_splash__GTouU&quot;]/form[1]/div[1]/div[@class=&quot;styles_responsiveAbsolutFix__bCkQO&quot;]/div[@class=&quot;styles_container__0Fbqk&quot;]/div[@class=&quot;styles_signInForm__i2b4C&quot;]/div[@class=&quot;styles_inputs__o1Xni&quot;]/div[@class=&quot;styles_sufixWrapper__qozVh&quot;]/input[@class=&quot;styles_input__sEMsJ&quot;]</value>
      <webElementGuid>ea73ea01-9718-4615-b2d0-7e26e465da6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>4cebb41f-a44a-448a-ba6e-c79f5e8ab55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>84ae6aab-5a73-476f-91b9-1eefbf813266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>54e7ee15-e12b-4583-8ae4-e4e0721cbc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'Insert your password']</value>
      <webElementGuid>27ab0036-bc91-4b58-81b4-9aabf229a221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
