<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your 6-digit code_styles_backgr_22ee6f</name>
   <tag></tag>
   <elementGuidId>7ac7f1bd-a103-4555-a276-25ac05e97098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styles_backgroundFocus__6BGT1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f54fb30-be3a-4de9-b377-d087e268e521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_backgroundFocus__6BGT1</value>
      <webElementGuid>c74476b2-a6c4-4b1a-a075-b3a47a41b275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>228ee628-83fb-4646-8d0d-b5683f33892f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>da7aadd0-454d-4e82-8c80-59932fba026d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_splash__GTouU&quot;]/form[1]/div[@class=&quot;styles_twoFactorContainer__IMV+w&quot;]/div[@class=&quot;styles_twoFactorForm__BqmYE&quot;]/div[1]/div[@class=&quot;styles_digitCode__8BMyw&quot;]/div[@class=&quot;styles_inputGroup__hUuTN&quot;]/input[@class=&quot;styles_backgroundFocus__6BGT1&quot;]</value>
      <webElementGuid>1f33cad0-f049-4d04-ba90-80847e3481e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>9a7d6783-09f5-46b7-8f8f-0498a461416a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div/div/input</value>
      <webElementGuid>88fe8f8b-4bf7-4708-a48e-e3df018b254a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fa4dc4bb-6f49-4ef0-af06-dc74fdb7853e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
