<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_user</name>
   <tag></tag>
   <elementGuidId>3690f42d-32fc-4b19-adcf-0029a279e017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_dropDownContent__DM62F</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef26b94d-d3b1-4986-9e65-394dde565621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_dropDownContent__DM62F</value>
      <webElementGuid>cd971e06-d606-4035-82ee-c88060efefbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testing a13</value>
      <webElementGuid>bac5faa9-c3aa-4502-aa2c-dd9e1cf676b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/header[1]/div[@class=&quot;styles_profile__bDv+H&quot;]/div[@class=&quot;styles_reference__1Uzek&quot;]/div[@class=&quot;styles_dropDownContent__DM62F&quot;]</value>
      <webElementGuid>c82ba1a6-1ae9-4fce-a544-06d5f738e59c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/div[3]/div/div</value>
      <webElementGuid>0c5191b8-7fb4-4b32-a06a-7fddeabe65b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settlements'])[1]/following::div[3]</value>
      <webElementGuid>1c03e172-5a81-4c94-b6ee-79dfec831e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lend/Borrow'])[1]/following::div[3]</value>
      <webElementGuid>73d1cae1-64ff-4982-8a50-d2a90144ebed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ta'])[1]/preceding::div[3]</value>
      <webElementGuid>d45bb744-9587-43e8-8d0a-7c4a7dc1545c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>ca1c60e1-50a1-40a3-9403-dc63d07f8599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'testing a13' or . = 'testing a13')]</value>
      <webElementGuid>8f936306-753d-4ac4-9291-2ad482f9daf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
