<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>my_wallets</name>
   <tag></tag>
   <elementGuidId>fcb92714-4a4d-41c4-b866-3e1299887ebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/div[3]/div/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1a1cb0a-5e71-4491-a831-79ad095bbc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-wallets</value>
      <webElementGuid>d548fa3c-c5bc-4d6c-9200-e0f021c9acbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Wallets</value>
      <webElementGuid>2af26e0e-35e2-48f0-8aba-4bfdd4b62e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/header[1]/div[@class=&quot;styles_profile__bDv+H&quot;]/div[@class=&quot;styles_reference__1Uzek&quot;]/div[@class=&quot;styles_menuWrapper__pdHNH&quot;]/ul[@class=&quot;styles_menu__RuT83&quot;]/li[@class=&quot;styles_menuItem__BZg8-&quot;]/a[1]</value>
      <webElementGuid>62b85231-64f0-4b1f-acea-558b2165706b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/div[3]/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>cf73dee1-90cf-45e2-a8e6-c1bc75bbd905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Wallets')]</value>
      <webElementGuid>7c35e3c2-e33c-4ccb-8d3d-63bdf3949dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balances &amp; Credits'])[1]/following::a[1]</value>
      <webElementGuid>9f3c6218-14b0-4211-902d-b55eff1bb2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Center'])[1]/preceding::a[1]</value>
      <webElementGuid>f2f73152-6bd8-4ca4-b0ff-79dee7f87670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::a[2]</value>
      <webElementGuid>03ae2a92-589f-44ae-84c1-17796c936e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Wallets']/parent::*</value>
      <webElementGuid>db40192a-e17a-4b0d-993a-90d0f7dcd8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-wallets')]</value>
      <webElementGuid>56b755bb-a4d3-4585-8f7a-56decefe32fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>f0249793-47a4-4c25-a6a2-0a3efe5ec09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-wallets' and (text() = 'My Wallets' or . = 'My Wallets')]</value>
      <webElementGuid>14ddaf1d-63ca-48f2-8cdb-763ff7fe1d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
