<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_collateral</name>
   <tag></tag>
   <elementGuidId>5666e30f-4d88-45e8-a1bb-d41a52e13f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_sufixWrapper__qozVh > input[name=&quot;collateral_value&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='collateral_value'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81cb1e32-4062-4e2d-99c2-8b35540e13b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1320baa7-4148-49dd-9069-9fa9748e5747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collateral_value</value>
      <webElementGuid>4dc4b0c8-039c-479c-9885-f479d33d1c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>field_none</value>
      <webElementGuid>e4280583-75c1-4e9f-9dd8-1b55be47806a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>5596fcb6-13d9-46c9-b528-ace15d2b7b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__sEMsJ</value>
      <webElementGuid>5219c3f3-a550-4128-b931-025473994c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e8df29e9-aa64-41b8-a659-ce25f872ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_lendBorrowContainer__oNH9F&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[@class=&quot;styles_formContent__hpD6+&quot;]/div[@class=&quot;styles_collateralRadioOptsLabel__-pXH8&quot;]/div[@class=&quot;styles_collateralValuesContainer__iLOrS&quot;]/div[@class=&quot;styles_collateralValue__CSjX2&quot;]/div[@class=&quot;styles_sufixWrapper__qozVh&quot;]/input[@class=&quot;styles_input__sEMsJ&quot;]</value>
      <webElementGuid>2345eb46-76f3-4638-a55c-e1580fc2787a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='collateral_value'])[7]</value>
      <webElementGuid>df41fc62-d9ac-48ec-bfc7-5fb9fef7d676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[8]/div/div[2]/div/input</value>
      <webElementGuid>9ceb56da-f518-4ffe-a4a4-ccf20568619c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/input</value>
      <webElementGuid>0d756537-9c2d-41f3-9c05-b3e4d5dc42d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'collateral_value']</value>
      <webElementGuid>b16d5eb3-c0ca-46c6-bd80-15ab7e6f8f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
