<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blockchain_eth</name>
   <tag></tag>
   <elementGuidId>b1025971-833f-44f8-9a31-ca18448a4768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_fieldInput__IDY-B</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/label/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31c729f1-015b-482a-af7f-e3532b681490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_fieldInput__IDY-B</value>
      <webElementGuid>f4873767-b474-49bd-8e11-cb8251810480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2ab18740-d5c8-48c8-b54d-9a92c620a7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_myBalanceHeader__8eqxI&quot;]/div[@class=&quot;styles_selectable__ja4NI&quot;]/div[@class=&quot;styles_modal__5D1PS styles_modal__dX4LE&quot;]/div[@class=&quot;styles_modalContainer__ognAv&quot;]/div[@class=&quot;styles_dialogContainer__ICG6E&quot;]/div[@class=&quot;styles_tokenAddressContainer__xR7hS&quot;]/label[1]/div[@class=&quot;styles_selectable__gksaM styles_customDisabled__d8wqy&quot;]/div[@class=&quot;styles_fieldInput__IDY-B&quot;]</value>
      <webElementGuid>2761f0f4-954b-4b76-ad79-7c61ac65397f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/label/div/div</value>
      <webElementGuid>563415ec-1c67-43c8-a686-232ddbb51664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please, enter the contract address'])[1]/following::div[3]</value>
      <webElementGuid>4ed8d286-3641-44be-9460-fc6327feef1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethereum'])[1]/preceding::div[1]</value>
      <webElementGuid>0ed22796-bb36-4506-a212-c8ea5ce89148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WBTC'])[1]/preceding::div[3]</value>
      <webElementGuid>05d8eec2-9636-40e0-8c57-8bac4aec413d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div</value>
      <webElementGuid>f5ee1beb-be0b-458f-96a6-b76c2278c66a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
