<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_chavo</name>
   <tag></tag>
   <elementGuidId>b75e034f-0a50-4335-8024-cdaf80e599c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[2]/div[3]/div/div[2]/div[2]/div[4]/ul/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>80db61c4-51cd-43f7-870b-ba08899d8d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_itemList__x9bnT</value>
      <webElementGuid>e6fc36d2-e750-42ac-8bd9-9af28e84bfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>li_elchavo_lootgnitset</value>
      <webElementGuid>ec4743fa-fa06-44f1-bed8-454e06b9c149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ElChavo Lootgnitset</value>
      <webElementGuid>d0b7df7a-3132-4ec6-9059-9cc7b0430444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_mainContent__VwuoZ&quot;]/div[@class=&quot;styles_wrapper__GF9VK&quot;]/div[@class=&quot;styles_buySellContainer__lJE32&quot;]/form[1]/div[@class=&quot;styles_card__yCIOH&quot;]/div[@class=&quot;styles_cardContainer__OD4EQ&quot;]/div[1]/div[@class=&quot;styles_flexWrapper__XSBX8&quot;]/div[@class=&quot;styles_targetCompaniesId__5-8mp&quot;]/div[@class=&quot;styles_selectable__68lJ1 styles_select__vbhfn&quot;]/div[@class=&quot;styles_modal__5D1PS&quot;]/div[@class=&quot;styles_modalContainer__ognAv styles_modal__dXwJj&quot;]/div[@class=&quot;styles_selectableList--container__Qwf6T&quot;]/ul[@class=&quot;styles_selectableList--ul__bSAEk&quot;]/li[@class=&quot;styles_itemList__x9bnT&quot;]</value>
      <webElementGuid>967b53af-1d23-40ec-9500-c2301cde7cb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div/div[2]/div[3]/div/div[2]/div[2]/div[4]/ul/li[5]</value>
      <webElementGuid>40be8988-da21-425d-991e-39c313f4eb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luciano Copado'])[1]/following::li[1]</value>
      <webElementGuid>4c0a59b6-0c1c-4d60-adb1-0161bf85d300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaston michel'])[1]/following::li[2]</value>
      <webElementGuid>b5ac59ba-2314-4c7c-ae88-35ca8c494e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Counterparty'])[1]/preceding::li[1]</value>
      <webElementGuid>ee4c1866-ed9c-44c2-b160-7a2d25642c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[5]</value>
      <webElementGuid>1fefce4a-4893-468d-b428-e5a67e7717c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ElChavo Lootgnitset' or . = 'ElChavo Lootgnitset')]</value>
      <webElementGuid>9521b86f-ab93-46de-8b6c-94fecd021db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
